### ISSUE TITLE
Need some help regarding labels

### ISSUE THREAD

**Issue by abdkhanstd** [PeiZhou26/Few-Shot-3D-Point-Cloud-Classification#1]
Hi, 
Thank you for sharing your work. I’m a bit confused with the **novel.json** and **base.json** files. 
For both files, the labels are not aligning. If it's possible, can you please help me? Do the labels for the same class in novel.json and base.json need to be the same? (most probably I'm getting it wrong.)

For example:
 label for **airplane** in **base.json** is **0**
 label for **bathtub** in **novel.json** is **0**

much appreciated. Thank you

**Comment by PeiZhou26** [comment]
Hi,
The labels for the same class in novel.json and base.json files are not the same. For few-shot learning tasks, the classes for training and classes for testing are disjoint, so there are 30 classes in the base.json(for training) and only 10 classes in the novel.json(for testing).

**Comment by abdkhanstd** [comment]
> Hi, The labels for the same class in novel.json and base.json files are not the same. For few-shot learning tasks, the classes for training and classes for testing are disjoint, so there are 30 classes in the base.json(for training) and only 10 classes in the novel.json(for testing).

Thank you so much for the swift response and clarification. 

Cheers!

**Comment by abdkhanstd** [comment]
Cheers
