### ISSUE TITLE
CUDA always out of memory

### ISSUE THREAD

**Issue by abdkhanstd** [PeiZhou26/Few-Shot-3D-Point-Cloud-Classification#2]
Hi, I always get this error for DGCNN and PointNet2 

CUDA out of memory. Tried to allocate 1.56 GiB (GPU 0; 14.75 GiB total capacity; 14.43 GiB already allocated; 154.81 MiB free; 14.46 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF)

I have tried multiple GPUs 24GB for about 08 machines etc, but the same issue. 
Also reduced batch size, workers, pin to memory, etc. Can you recommend 

I need your further guidance. Thank you

**Comment by PeiZhou26** [comment]
I don't recall exactly how I addressed this issue. The total GPU memory demand for the entire experiment shouldn't exceed 40GB. You could potentially try the command torch.cuda.empty_cache().

**Comment by abdkhanstd** [comment]
> I don't recall exactly how I addressed this issue. The total GPU memory demand for the entire experiment shouldn't exceed 40GB. You could potentially try the command torch.cuda.empty_cache().

Thank you for your humble guidance. Unfortunately, I'm unable to parallelize the code over 04 x 24 GB GPUs.
